sudo: required

language: generic

services:
  - docker
  - xvfb

env:
  matrix:
    - TAG=zbarcam-linux DOCKERFILE=dockerfiles/Dockerfile-linux COMMAND='make test'
    - TAG=zbarcam-android DOCKERFILE=dockerfiles/Dockerfile-android COMMAND='buildozer android debug'

before_script:
  - docker build --tag=$TAG --file=$DOCKERFILE --build-arg CI .

script:
  - travis_wait 30 docker run --env-file dockerfiles/env.list -v /tmp/.X11-unix:/tmp/.X11-unix $TAG $COMMAND
